### ISSUE TITLE
Double access to web service

### ISSUE THREAD

**Issue by seitza** [Rostlab/SNAP2#1]
The SNAP2 tool is accessible via two adresses: _https://rostlab.org/services/snap/_ and _https://rostlab.org/services/snap2web/_ . 

Maybe you want to close one (maybe not) or maybe you want to close both and create a new one with the most convenient name **https://rostlab.org/services/snap2/** ? Either way, please inform us, so we can update the Readme.md

**Comment by juanmirocks** [comment]
Sent email to Max:

```
Hey Max,

you will find this question relevant posed by the students. Could you please give an answer on the github issue itself? 

--> https://github.com/Rostlab/SNAP2/issues/1

I can add you to the rostlab group and you then can be the maintainer of the tool
```

**Comment by hechtm** [comment]
https://rostlab.org/services/snap/ this we keep for legacy reasons, as some users have a bookmark for the previous version. 
The other one is the one we published in: http://www.ncbi.nlm.nih.gov/pubmed/26110438
Therefore, we should keep both
