### ISSUE TITLE
Access to svn repo

### ISSUE THREAD

**Issue by seitza** [Rostlab/SNAP2#1]
@jmcejuela 
We did not yet receive any permission to access the svn folders, did we? In our particular case ( @leidigl , seitza), we want to checkout svn+ssh://rostlab.org/mnt/project/subversion/snap2/trunk

Can we get accounts on the host, or do you want to get the ssh keys?

**Comment by jmcejuela** [comment]
Your issue should already be solved. See: https://github.com/Rostlab/PP2_CS_WS_2015-16/issues/3
