### ISSUE TITLE
Organize branches

### ISSUE THREAD

**Issue by juanmirocks** [Rostlab/SNAP2#5]
At this point I see many branches and it's not entirely clear what is what.

I suggest to please:
- [x] Just have **master** & **develop** as main branches
- [x] All other temporal branches should follow the naming as **feature/<featureName>**
- [x] The README should go directly to **develop** branch

**Comment by leidigl** [comment]
Cleaned up the branching structure.

**Comment by juanmirocks** [comment]
Excellent. Thank you.

I put `develop` branch as default
