### ISSUE TITLE
Mistake on rostlab page

### ISSUE THREAD

**Issue by leidigl** [Rostlab/SNAP2#7]
https://rostlab.org/owiki/index.php/Snap2

At the end of this page (paragraph "Accuracy of functional effect prediction") it is stated that the bootstrapping sets were gained with replacement. However, the paper (Hecht et al., BMC Genomics, 2015) states without replacement.

**Comment by juanmirocks** [comment]
Good finding :+1: . I will correct this myself

**Comment by juanmirocks** [comment]
Fixed
